package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"

	"github.com/jaovw/go-graphql-api/graph/model"
)

// Persons is the resolver for the persons field.
func (r *queryResolver) Persons(ctx context.Context) ([]*model.Person, error) {
	person := &model.Person{
		ID:     "id-01",
		Name:   "Person 01",
		Age:    25,
		IsMale: false,
	}

	persons := []*model.Person{
		person,
	}

	return persons, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
